# Generated by Django 5.2.1 on 2025-05-27 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='WorkerActivity',
        ),
    ]
